### ISSUE TITLE
Changing line number height for current line

### ISSUE THREAD

**Issue by kiranandcode** [Harith163/TransSide-theme#1]
hihi! Thanks for writing and publishing this theme!  It's really awesome!!!

I just had a question/suggestion for the theme -- is there a particular reason that the theme sets a different line height for the current line number?:

https://github.com/Harith163/TransSide-theme/blob/a58e43a4425ffdd765d110d6e3e44ef1e0c6d3de/TransSide.el#L81

For me, I found this to be a little disorienting and made it hard to work with indentation sensitive languages, because the change in line height would cause the current line to be offset, but I understand that this might be a deliberate decision, etc. and I can totally just change it in my own local version.

**Comment by skye-repos** [comment]
Hi Gopi!

Thank you so much for pointing this out! I'm not sure why I did it that way to be honest.

If my memory serves me correctly, the `linum` face came from a non-builtin package called `linum-relative`. In retrospect I don't think that is the right thing for this theme.

Having said that, the linum face should only affect the size of the line-numbers displayed in the marging. It might be that there is something conflicting in your setup that is causing this issue.

Could you share some screenshots so that I can better understand what we are working with? 

Best,
KSH

**Comment by kiranandcode** [comment]
Hihi Kaushik! (btw, my name is Kiran!!) Thanks for the response!!

Ooh, yup, it could be something arising from my own setup, maybe I'm using a custom line numbers mode? hmmm.... I'm not too sure, and I haven't looked into it too much yet.


Well, anyway, here's a screenshot of what happens with 0.85 line height:

![Screenshot from 2024-05-08 14-31-59](https://github.com/Harith163/TransSide-theme/assets/23038502/cae04445-44c0-40f2-8089-23c48fda268d)

Versus how it looks with 1.0 line height:

![Screenshot from 2024-05-08 14-32-32](https://github.com/Harith163/TransSide-theme/assets/23038502/fcd4aa43-2b4f-4804-ad7d-6efa7e202916)

**Comment by skye-repos** [comment]
Hi Kiran (sorry for the mixup haha),

Just played around with it but I found it tough to replicate. I did see the indentation issue you mentioned appear when i had both `linum-relative-mode` and `display-line-numbers-mode` active.

For the time being I've pushed a commit removing the mention of height for linum. Check it out and let me know if that fixes the issue for you.

In the meantime, I plan on rewriting the theme ground up to be more predictable to avoid issues like this, taking inspiration from how rougier's nano-emacs does things. I'll share a snippet for you to try out shortly

**Comment by skye-repos** [comment]
> Hihi Kaushik! (btw, my name is Kiran!!) Thanks for the response!!
> 
> Ooh, yup, it could be something arising from my own setup, maybe I'm using a custom line numbers mode? hmmm.... I'm not too sure, and I haven't looked into it too much yet.
> 
> Well, anyway, here's a screenshot of what happens with 0.85 line height:
> 
> ![Screenshot from 2024-05-08 14-31-59](https://private-user-images.githubusercontent.com/23038502/328779956-cae04445-44c0-40f2-8089-23c48fda268d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTA0NjksIm5iZiI6MTcxNTE1MDE2OSwicGF0aCI6Ii8yMzAzODUwMi8zMjg3Nzk5NTYtY2FlMDQ0NDUtNDRjMC00MGYyLTgwODktMjNjNDhmZGEyNjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA2MzYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YmIyOThiMTE0ZmVjYmZiNjVmMDE3NzE2NTU0MzY1YTk5YzU4MTk0MzVkNjY3ZjY4OTcyMDEyYzZmZDcxMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mVPrDiZmWajyhrKHT4p4KTC-0D8VlAbTGZmEvn2Yb9c)
> 
> Versus how it looks with 1.0 line height:
> 
> ![Screenshot from 2024-05-08 14-32-32](https://private-user-images.githubusercontent.com/23038502/328780198-fcd4aa43-2b4f-4804-ad7d-6efa7e202916.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTA0NjksIm5iZiI6MTcxNTE1MDE2OSwicGF0aCI6Ii8yMzAzODUwMi8zMjg3ODAxOTgtZmNkNGFhNDMtMmI0Zi00ODA0LWFkN2QtNmVmYTdlMjAyOTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA2MzYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ZTIwMjg5MWRhZjc5OTdiZDNkNmZhZDc1YjkzZDc5Yjc3Y2E1MWY5ZDdlZmU4YzRjYWQ0ZjRjMGQ1YTQ5MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.'-H2nII36eelrmhnihOM-B0DjtJxGaas)

Oh this is interesting, your primary text color seems to be different from the one I've set. Can you check you don't have any other themes enabled? You can do `M-x disable-theme` and it should list all the active themes you have. Emacs lets you load multiple themes at once so it often conflicts like this.

It's good practice to use `load-theme` instead of `enable-theme` for this reason, but I usually go one step further and manually `disable-theme` then `load-theme`.

**Comment by kiranandcode** [comment]
> Hi Kiran (sorry for the mixup haha),
No worries!!!

> Just played around with it but I found it tough to replicate. I did see the indentation issue you mentioned appear when i had both `linum-relative-mode` and `display-line-numbers-mode` active.
> 
> For the time being I've pushed a commit removing the mention of height for linum. Check it out and let me know if that fixes the issue for you.

Oooh, awesome!! Thanks so much, yepp, just pulled it and it does fix the issue!

> In the meantime, I plan on rewriting the theme ground up to be more predictable to avoid issues like this, taking inspiration from how rougier's nano-emacs does things. I'll share a snippet for you to try out shortly

Ohh, looking forward to it!!

Thanks for fixing this so quickly!!!

**Comment by kiranandcode** [comment]
> Oh this is interesting, your primary text color seems to be different from the one I've set. Can you check you don't have any other themes enabled? You can do `M-x disable-theme` and it should list all the active themes you have. Emacs lets you load multiple themes at once so it often conflicts like this.
> 
> It's good practice to use `load-theme` instead of `enable-theme` for this reason, but I usually go one step further and manually `disable-theme` then `load-theme`. (although  it could be that my overriden disable-theme is hiding things lol)

Hmm... I ran disable-theme although it seems the only loaded theme was TransSide. I think the screenshot I shared was from inside a def-macro, so the entire block was quoted and hence had the blue font --- here's a screenshot of more code, with a normal color and also the blue color of the quoted blocks:

![Screenshot from 2024-05-08 14-42-36](https://github.com/Harith163/TransSide-theme/assets/23038502/26aaeaaa-9943-4ef1-bd2a-43d02ebc86c9)

Does that seem accurate to what you expect?

**Comment by kiranandcode** [comment]
Ah, oh wait it does still look different from your screenshot!!!

I think I figured out the cause - I'm using `lisp-extra-font-lock-mode` (my .emacs.d. is ancienttt and contains random stuff from ages ago that even I've forgotten lol) which causes quoted blocks and stuff to be coloured differently -- turning it off makes the font match your screenshot I think:

![Screenshot from 2024-05-08 14-49-39](https://github.com/Harith163/TransSide-theme/assets/23038502/e62baa54-0df1-459b-8556-7763287c68a6)

**Comment by kiranandcode** [comment]
Anyway, thanks so much for making the theme and updating this so quickly!!! There are suprisngly not as many trans-themed emacs themes as I would have expected, so it was great to find this one!!

**Comment by skye-repos** [comment]
Hi Kiran,

Try out this repo. This is the direction i want to take the theme consistency wise (while sticking with the original vibe of course haha). I have been using this setup for a bit now. I haven't had the need to use emacs for a while now, but its quite easy on the eyes.

https://github.com/Harith163/nano-TransSide.git

Best,
KSH

**Comment by kiranandcode** [comment]
Omg!!! wowow!!! This looks amazinggg!!! I hadn't heard about nano-emacs before, but it's really fab. Plus transside! Perfectt!! Amazingggg!!!
